export const Titles = {
	sectionOne: 'ENTER YOUR ADDRESS',
	sectionTwo: 'SPECIFIC INFORMATION',
	sectionThree: 'CONTACT INFORMATION',
	crossStreet:'CROSS STREET',
	FirstName: 'FIRST NAME',
	LastName: 'LAST NAME',
	Phone: 'PRIMARY PHONE NUMBER',
	Email: 'E-MAIL',
	ConfirmEmail: 'CONFIRM E-MAIL',
	AppointmentDate: 'APPOINTMENT DATE',
		overideAddressValidation:'I certify that this request is not for a commercial business',
	PickUpLocation: 'PICKUP STREET',
	 LocationId: 'PICKUP LOCATION',
	 SuccessMessage: "Success! Your response No. is: ",
	 FailureMessage:"Please make sure your message is correct.",
}

export const formObject = {
	"RequestId": 0,
	"strRequestId": "",
	"SRNumber": "",
	"FirstName": "",
	"LastName": "",
	"Phone": "",
	"Email": "",
	"ConfirmEmail": "",
	"Borough": "",
	"BuildingNumber": "",
	"Street": "",
	"District": "",
	"DistrictName": "",
	"PickUpLocation": "",
	"LocationId":"",
	"BBL": "",
	"CrossStreets": "",
	"AppointmentDate": "",
	"CreatedDate": "",
	"LastUpdatedDate": "",
	"UserName": "",
	"Source": "",
	"StatusId": 0,
	"PickupRequestItems": [],
	"categories": [
								{
									"$id": "1",
							    "CategoryId": 2,
							    "Category": "Furniture -Non-metal bed frames and non-recyclable items larger than 4ft. x 3ft.",
							    "DashboardCategory": "Furniture",
							    "SubCategoryId": 0,
							    "SubCategory": null,
							    "DashboardSubCategory": null,
							    "RequestedQty": 0,
							    "PickedUpQty": 0,
							    "PickupRequestSubItems": null,
									"hasSubCategory": [
						  {
						    "$id": "1",
						    "CategoryId": 2,
						    "Category": null,
						    "DashboardCategory": null,
						    "SubCategoryId": 1,
						    "SubCategory": "Mattresses and box springs (You must seal any mattress or box spring in a plastic bag before placing it out for bulk collection to prevent the spread of bed bugs. If you do not dispose of mattresses or box springs properly, it will not be collected, and you may receive a $100 fine.)",
						    "DashboardSubCategory": "Mattresses and box springs",
						    "RequestedQty": 0,
						    "PickedUpQty": 0,
						    "PickupRequestSubItems": null,
						    "hasSubCategory": 0
						  },
						  {
						    "$id": "2",
						    "CategoryId": 2,
						    "Category": null,
						    "DashboardCategory": null,
						    "SubCategoryId": 2,
						    "SubCategory": "Couch",
						    "DashboardSubCategory": "Couch",
						    "RequestedQty": 0,
						    "PickedUpQty": 0,
						    "PickupRequestSubItems": null,
						    "hasSubCategory": 0
						  },
						  {
						    "$id": "3",
						    "CategoryId": 2,
						    "Category": null,
						    "DashboardCategory": null,
						    "SubCategoryId": 3,
						    "SubCategory": "Tables",
						    "DashboardSubCategory": "Tables",
						    "RequestedQty": 0,
						    "PickedUpQty": 0,
						    "PickupRequestSubItems": null,
						    "hasSubCategory": 0
						  },
						  {
						    "$id": "4",
						    "CategoryId": 2,
						    "Category": null,
						    "DashboardCategory": null,
						    "SubCategoryId": 4,
						    "SubCategory": "Bed frames",
						    "DashboardSubCategory": "Bed frames",
						    "RequestedQty": 0,
						    "PickedUpQty": 0,
						    "PickupRequestSubItems": null,
						    "hasSubCategory": 0
						  },
						  {
						    "$id": "5",
						    "CategoryId": 2,
						    "Category": null,
						    "DashboardCategory": null,
						    "SubCategoryId": 5,
						    "SubCategory": "Dressers",
						    "DashboardSubCategory": "Dressers",
						    "RequestedQty": 0,
						    "PickedUpQty": 0,
						    "PickupRequestSubItems": null,
						    "hasSubCategory": 0
						  },
						  {
						    "$id": "6",
						    "CategoryId": 2,
						    "Category": null,
						    "DashboardCategory": null,
						    "SubCategoryId": 12,
						    "SubCategory": "Other",
						    "DashboardSubCategory": "Other",
						    "RequestedQty": 0,
						    "PickedUpQty": 0,
						    "PickupRequestSubItems": null,
						    "hasSubCategory": 0
						  }
						]
		}, {
			"$id": "2",
	    "CategoryId": 3,
	    "Category": "Home improvement Waste - Small one & two family home do-it-yourself projects only (Work on income properties, fee for service and contractor material must be serviced by hiring a private carter or dumpster)",
	    "DashboardCategory": "Home improvement Waste",
	    "SubCategoryId": 0,
	    "SubCategory": null,
	    "DashboardSubCategory": null,
	    "RequestedQty": 0,
	    "PickedUpQty": 0,
	    "PickupRequestSubItems": null,
			"hasSubCategory": [
									  {
									    "$id": "1",
									    "CategoryId": 3,
									    "Category": null,
									    "DashboardCategory": null,
									    "SubCategoryId": 7,
									    "SubCategory": "Carpet, rugs and lumber (no larger than 2 ft. high and 4 ft. long bales)",
									    "DashboardSubCategory": "Carpet, rugs and lumber",
									    "RequestedQty": 0,
									    "PickedUpQty": 0,
									    "PickupRequestSubItems": null,
									    "hasSubCategory": 0
									  },
									  {
									    "$id": "2",
									    "CategoryId": 3,
									    "Category": null,
									    "DashboardCategory": null,
									    "SubCategoryId": 8,
									    "SubCategory": "Construction material (do-it-yourself)",
									    "DashboardSubCategory": "Construction material (do-it-yourself)",
									    "RequestedQty": 0,
									    "PickedUpQty": 0,
									    "PickupRequestSubItems": null,
									    "hasSubCategory": 0
									  },
									  {
									    "$id": "3",
									    "CategoryId": 3,
									    "Category": null,
									    "DashboardCategory": null,
									    "SubCategoryId": 9,
									    "SubCategory": "Windows and Mirrors",
									    "DashboardSubCategory": "Windows and Mirrors",
									    "RequestedQty": 0,
									    "PickedUpQty": 0,
									    "PickupRequestSubItems": null,
									    "hasSubCategory": 0
									  },
									  {
									    "$id": "4",
									    "CategoryId": 3,
									    "Category": null,
									    "DashboardCategory": null,
									    "SubCategoryId": 10,
									    "SubCategory": "Cabinets",
									    "DashboardSubCategory": "Cabinets",
									    "RequestedQty": 0,
									    "PickedUpQty": 0,
									    "PickupRequestSubItems": null,
									    "hasSubCategory": 0
									  },
									  {
									    "$id": "5",
									    "CategoryId": 3,
									    "Category": null,
									    "DashboardCategory": null,
									    "SubCategoryId": 11,
									    "SubCategory": "Doors",
									    "DashboardSubCategory": "Doors",
									    "RequestedQty": 0,
									    "PickedUpQty": 0,
									    "PickupRequestSubItems": null,
									    "hasSubCategory": 0
									  }
									]

		},
	],
}
