export const Titles = {
  sectionOne: 'WHERE IS THE COLLECTION BIN LOCATED',
  sectionTwo: 'BIN OWNER INFORMATION',
  sectionThree: 'PROPERTY OWNER INFORMATION',
  sectionFour: 'BIN INFORMATION',
  AdditionalLocationInfo: "ADDITIONAL LOCATION INFORMATION (OPTIONAL)",
  BinOwnerCompanyName: 'COMPANY NAME',
  BinOwnerApartment: 'FLOOR/SUITE/APT',
  BinOwnerFirstName: 'CONTACT FIRST NAME',
  BinOwnerLastName: 'CONTACT LAST NAME',
  BinOwnerTitle: 'CONTACT TITLE/ROLE',
  BinOwnerPhone: 'CONTACT PHONE',
  BinOwnerEmail: 'CONTACT EMAIL',
  BinOwnerAddressAsEntered: 'COMPANY ADDRESS',
  PropertyOwnerCompanyName: 'PROPERTY NAME',
  PropertyOwnerCompanyAddressAsEntered: 'PROPERTY ADDRESS',
  PropertyOwnerApartment: 'FLOOR/SUITE/APT',
  PropertyOwnerFirstName: 'CONTACT FIRST NAME',
  PropertyOwnerLastName: 'CONTACT LAST NAME',
  PropertyOwnerTitle: 'CONTACT TITLE/ROLE',
  PropertyOwnerPhone: 'CONTACT PHONE',
  PropertyOwnerEmail: 'CONTACT EMAIL',
  DescribeBinAppearances: 'DESCRIBE BIN APPEARANCE (OPTIONAL)',
  ClothingCollected: 'Clothing',
  ShoesCollected: 'Shoes',
  AccessoriesCollected: 'Accessories (purses, hats, belts, scarves, gloves, etc)',
  BeddingCollected: 'Bedding and lines',
  TowelsCollected: 'Towels',
  CoatsCollected: 'Coats',
  RugsCollected: 'Rugs',
  OtherCollected: 'Other',
  OtherCollecdtedMaterialDescribe: 'OTHER COLLECTED MATERIAL',
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
  RequiredFieldMessage: 'This field is required',
}


export const formObject = {

  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "AdditionalLocationInfo": null,
  "BinOwnerCompanyName": null,
  "BinOwnerStreet": null,
  "BinOwnerApartment": null,
  "BinOwnerCity": null,
  "BinOwnerState": null,
  "BinOwnerZip": null,
  "BinOwnerFirstName": null,
  "BinOwnerLastName": null,
  "BinOwnerTitle": null,
  "BinOwnerPhone": null,
  "PropertyOwnerCompanyName": null,
  "PropertyOwnerStreet": null,
  "PropertyOwnerApartment": null,
  "PropertyOwnerCity": null,
  "PropertyOwnerState": null,
  "PropertyOwnerZip": null,
  "PropertyOwnerFirstName": null,
  "PropertyOwnerLastName": null,
  "PropertyOwnerTitle": null,
  "PropertyOwnerPhone": null,
  "PropertyOwnerEmail": null,
  "DescribeBinAppearances": null,
  "BinOwnerContactInfoDisplayed": null,
  "ClothingCollected": false,
  "ShoesCollected": false,
  "AccessoriesCollected": false,
  "BeddingCollected": false,
  "TowelsCollected": false,
  "CoatsCollected": false,
  "RugsCollected": false,
  "OtherCollected": false,
  "OtherCollecdtedMaterialDescribe": null,
  "IsManagedByANonProfit": null,
  "ReceivedWrittenPermission": null,
  "Source": null,
  "CreatedDate": "0001-01-01T00:00:00",
  "ServiceRequestStatusId": 0,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null
}