export const Titles = {
  sectionOne: 'WHERE IS THE COLLECTION BIN LOCATED',
  sectionTwo: 'BIN OWNER INFORMATION',
  sectionThree: 'ORGANIZATION / SPONSORSHIP ON BIN',
  sectionFour: 'CONTACT INFORMATION',
  AdditionalLocationInfo: 'ADDITIONAL LOCATION INFORMATION (OPTIONAL)',
  BinOwnerCompanyName: 'COMPANY',
  BinColor: 'COLOR',
  ObservationDate: 'OBSERVATION DATE',
  BinTypeId: 'TYPE',
  OtherCollectionDescribe: 'DESCRIBE OTHER COLLECTION',
  OrganizationName: 'ORGANIZATION/SPONSOR NAME',
  OrganizationAddressAsEntered: 'ADDRESS',
  OrganizationPhone: 'PHONE',
  OrganizationApartment: 'FLOOR/SUITE/APT (OPTIONAL)',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Phone: 'PHONE',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
  RequiredFieldMessage: 'This field is required',
}


export const formObject = {  

  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "AdditionalLocationInfo": null,
  "BinOwnerCompanyName": null,
  "BinOwnerStreet": null,
  "BinOwnerApartment": null,
  "BinOwnerCity": null,
  "BinOwnerState": null,
  "BinOwnerZip": null,
  "BinOwnerFirstName": null,
  "BinOwnerLastName": null,
  "BinOwnerTitle": null,
  "BinOwnerPhone": null,
  "PropertyOwnerCompanyName": null,
  "PropertyOwnerStreet": null,
  "PropertyOwnerApartment": null,
  "PropertyOwnerCity": null,
  "PropertyOwnerState": null,
  "PropertyOwnerZip": null,
  "PropertyOwnerFirstName": null,
  "PropertyOwnerLastName": null,
  "PropertyOwnerTitle": null,
  "PropertyOwnerPhone": null,
  "PropertyOwnerEmail": null,
  "DescribeBinAppearances": null,
  "BinOwnerContactInfoDisplayed": false,
  "ClothingCollected": false,
  "ShoesCollected": false,
  "AccessoriesCollected": false,
  "BeddingCollected": false,
  "TowelsCollected": false,
  "CoatsCollected": false,
  "RugsCollected": false,
  "OtherCollected": false,
  "OtherCollecdtedMaterialDescribe": null,
  "IsManagedByANonProfit": false,
  "ReceivedWrittenPermission": false,
  "Source": null,
  "CreatedDate": "0001-01-01T00:00:00",
  "ServiceRequestStatusId": 0,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null
  
}