export const CHANGE_ROUTE = 'CHANGE_ROUTE';

//Home Section
export const FETCH_EVENT_SUB_LIST = 'FETCH_EVENT_SUB_LIST';
export const FETCH_EVENT_DETAILS = 'FETCH_EVENT_DETAILS';

//Resources Section
export const RESOURCES_LANDING_SECTION = 'RESOURCES_LANDING_SECTION';
export const CARD_DETAILS = 'CARD_DETAILS';

//Press Release
export const FETCH_PRESS_RELEASE_DETAILS = 'FETCH_PRESS_RELEASE_DETAILS';
export const FETCH_PRESS_RELEASE_LIST = 'FETCH_PRESS_RELEASE_LIST';

//Reusable Components
export const DROPDOWN_LIST = 'DROPDOWN_LIST';
export const FETCH_MEDIA = 'FETCH_MEDIA';
export const FETCH_SUB_SECTION_HEADER = 'FETCH_SUB_SECTION_HEADER';

//Bureaus
export const FETCH_BUREAUS_DETAILS = 'FETCH_BUREAUS_DETAILS';

//Locations
export const FETCH_LOCATION_LIST = 'FETCH_LOCATION_LIST';

//Forms
export const FETCH_FORM_GET_COMPOST_REQUEST = 'FETCH_FORM_GET_COMPOST_REQUEST';
export const POST_FORM_COMPOST_REQUEST = 'POST_FORM_COMPOST_REQUEST';

//errors
export const ERROR_LOADING_REQUEST = 'ERROR_LOADING_REQUEST';
