export const Titles = {
  sectionOne: 'WHERE IS THE BIN LOCATED',
  sectionTwo: 'BIN INFORMATION',
  sectionThree: 'ORGANIZATION / SPONSORSHIP ON BIN',
  sectionFour: 'CONTACT INFORMATION',
  BinLocationAdditionalLocationInfo: 'ADDITIONAL LOCATION INFORMATION (OPTIONAL)',
  BinColor: 'COLOR',
  ObservationDate: 'OBSERVATION DATE',
  BinTypeId: 'TYPE',
  OtherCollectionDescribe: 'DESCRIBE OTHER COLLECTION',
  OrganizationName: 'ORGANIZATION/SPONSOR NAME',
  OrganizationAddressAsEntered: 'ADDRESS',
  OrganizationPhone: 'PHONE',
  OrganizationApartment: 'FLOOR/SUITE/APT (OPTIONAL)',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Phone: 'PHONE',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
  RequiredFieldMessage: 'This field is required',
  BinLocationAddressAsEntered: 'NEAREST ADDRESS',
}


export const formObject = {  
  "BinLocationAddressAsEntered": null,
  "BinLocationHouseNumber": null,
  "BinLocationStreet": null,
  "BinLocationApartment": null,
  "BinLocationBorough": null,
  "BinLocationCity": null,
  "BinLocationState": null,
  "BinLocationZip": null,
  "BinLocationAdditionalLocationInfo": null,
  "BinColor": null,
  "ObservationDate": "0001-01-01T00:00:00",
  "BinTypeList": [
    {
      "Id": 0,
      "Name": "Select One",
      "DisplayName": "Select One",
      "Selected": false
    },
    {
      "Id": 1,
      "Name": "Clothing Collection",
      "DisplayName": "Clothing Collection",
      "Selected": false
    },
    {
      "Id": 2,
      "Name": "Shoe Collection",
      "DisplayName": "Shoe Collection",
      "Selected": false
    },
    {
      "Id": 3,
      "Name": "Other Collection",
      "DisplayName": "Other Collection",
      "Selected": false
    }
  ],
  "BinTypeId": 0,
  "BinType": null,
  "OtherCollectionDescribe": null,
  "OrganizationName": null,
  "OrganizationAddressAsEntered": null,
  "OrganizationHouseNumber": null,
  "OrganizationStreet": null,
  "OrganizationApartment": null,
  "OrganizationBorough": null,
  "OrganizationCity": null,
  "OrganizationState": null,
  "OrganizationZip": null,
  "OrganizationPhone": null,
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "Source": null,
  "CreatedDate": "0001-01-01T00:00:00",
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "FullName": null,
  "FullNameLastFirst": null,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null
}