export const Titles = {
	sectionOne: 'ENTER YOUR ADDRESS',
	sectionTwo: 'SPECIFIC INFORMATION',
	sectionThree: 'CONTACT INFORMATION',
	FirstName: 'FIRST NAME',
	LastName: 'LAST NAME',
	Phone: 'PRIMARY PHONE NUMBER',
	Email: 'E-MAIL',
	ConfirmEmail: 'CONFIRM E-MAIL',
	AppointmentDate: 'APPOINTMENT DATE',
	RecyclingLocation: 'RECYCLING LOCATION',
	SuccessMessage: "Success! Your response No. is: ",
	FailureMessage:"Please make sure your message is correct.",
}

export const formObject = {
	"RequestId": 0,
	"strRequestId": "",
	"SRNumber": "",
	"FirstName": "",
	"LastName": "",
	"Phone": "",
	"Email": "",
	"ConfirmEmail": "",
	"Borough": "",
	"BuildingNumber": "",
	"Street": "",
	"District": "",
	"DistrictName": "",
	"PickUpLocation": "",
	"BBL": "",
	"CrossStreets": "",
	"AppointmentDate": "",
	"CreatedDate": "",
	"LastUpdatedDate": "",
	"UserName": "",
	"Source": "DSNY",
	"StatusId": 0,
	"AppointmentItems": [],
	 "categories": [
    {
      "$id": "1",
      "AppliancesId": 1,
      "Category": "Air conditioner",
      "RequestedQty": 0,
    },
    {
      "$id": "2",
      "AppliancesId": 2,
      "Category": "Dehumidifier",
    "RequestedQty": 0,
    },
    {
      "$id": "3",
      "AppliancesId": 3,
      "Category": "Freezer",
      "RequestedQty": 0,
    },
    {
      "$id": "4",
      "AppliancesId": 4,
      "Category": "Refrizirator",
      "RequestedQty": 0,
    },
    {
      "$id": "5",
      "AppliancesId": 5,
      "Category": "Water cooler",
      "RequestedQty": 0,
    }
  ],
}
