export const Titles = {
	sectionOne: 'ENTER YOUR ADDRESS',
	sectionTwo: 'SPECIFIC INFORMATION',
	sectionThree: 'CONTACT INFORMATION',
	FirstName: 'FIRST NAME',
	LastName: 'LAST NAME',
	Phone: 'PRIMARY PHONE NUMBER',
	Email: 'E-MAIL',
	ConfirmEmail: 'CONFIRM E-MAIL',
	AppointmentDate: 'APPOINTMENT DATE',
	RecyclingLocation: 'RECYCLING LOCATION',
}

export const formObject = {
	"RequestId": 0,
	"strRequestId": "",
	"SRNumber": "",
	"FirstName": "",
	"LastName": "",
	"Phone": "",
	"Email": "",
	"ConfirmEmail": "",
	"Borough": "",
	"BuildingNumber": "",
	"Street": "",
	"District": "",
	"DistrictName": "",
	"PickUpLocation": "",
	"BBL": "",
	"CrossStreets": "",
	"AppointmentDate": "",
	"CreatedDate": "",
	"LastUpdatedDate": "",
	"UserName": "",
	"Source": "",
	"StatusId": 0,
	"PickupRequestItems": [],
	 "categories": [
    {
      "$id": "1",
      "CategoryId": 1,
      "Category": "Air conditioner",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory":0
    },
    {
      "$id": "2",
      "CategoryId": 17,
      "Category": "Dehumidifier",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory":0
    },
    {
      "$id": "3",
      "CategoryId": 3,
      "Category": "Freezer",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "4",
      "CategoryId": 4,
      "Category": "Refrizirator",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "5",
      "CategoryId": 5,
      "Category": "Water cooler",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    }
  ],
}
