export const Titles = {
  sectionOne: 'DESCRIBE SETOUT LOCATION OF RECYCLABLE MATERIAL',
  sectionTwo: 'SPECIFIC INFORMATION',
  sectionThree: 'CONTACT INFORMATION',
  AdditionalLocationInfo: "ADDITIONAL LOCATION INFORMATION (OPTIONAL)",
  DebrisInsideLot: 'Yes, debris inside the lot',
  DebrisInFrontOfLot: 'Yes, debris in front of the lot',
  VehiclesOnLot: 'Yes, vehicles on the lot',
  IsAnonymous: 'I would like to remain anonymous',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL',
  Phone: 'PHONE',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
  RequiredFieldMessage: 'This field is required',
}


export const formObject = {

  "AdditionalLocationInfo": null,
  "DebrisInsideLot": false,
  "DebrisInFrontOfLot": false,
  "VehiclesOnLot": false,
  "MediaFiles": [
    {
      "Id": 0,
      "DetailRecordId": 0,
      "FileName": null,
      "URI": null
    }
  ],
  "IsAnonymous": false,
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "ServiceRequestStatusId": 0,
  "Source": null,
  "CreatedDate": "0001-01-01T00:00:00",
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "FullName": null,
  "FullNameLastFirst": null,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null,
  "files1": [],
  "files2": [],
  "files3": []
}