export const Titles = {
  sectionOne: 'WHERE IS THE LITTER BASKET LOCATED ?',
  sectionTwo:'PARTICIPANT INFORMATION',
  sectionThree:'CONTACT INFORMATION',
  BasketAdditionalLocationInfo:'ADDITIONAL LOCATION INFORMATION',
  BusinessName:'BUSINESS/ORGANIZATION NAME',
  BusinessAddressAsEntered:'ADDRESS',
  AddressAsEntered:'NEARST ADDRESS',
  BusinessApartment:'FLOOR/APT/SUITE',
  FirstName:'FIRST NAME',
  LastName:'LAST NAME',
  Email:'EMAIL',
  confirmEmail:'CONFIRM EMAIL',
  Phone:'PHONE',
  Message: "MESSAGE",
  formTitle:'Equal Employment Opportunity Complaint',
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
  
}


export const formObject = {
  
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "ServiceRequestStatusId": 1,
  "BasketAddressAsEntered": null,
  "AddressAsEntered":null,
  "BasketHouseNumber": null,
  "BasketStreet": null,
  "BasketApartment": null,
  "BasketBorough": null,
  "BasketCity": null,
  "BasketState": "NY",
  "BasketZip": null,
  "BasketAddressText": ", NY",
  "BasketAddressTextOneLine": ", NY",
  "BasketAdditionalLocationInfo": null,
  "BusinessName": null,
  "BusinessAddressAsEntered": null,
  "BusinessHouseNumber": null,
  "BusinessStreet": null,
  "BusinessApartment": null,
  "BusinessBorough": null,
  "BusinessCity": null,
  "BusinessState": "NY",
  "BusinessZip": null,
  "BusinessAddressText": ", NY",
  "BusinessAddressTextOneLine": ", NY",
  "CreatedDate": "0001-01-01T00:00:00",
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "confirmEmail":null,
  "FullName": null,
  "FullNameLastFirst": null
  
}