export const Titles = {
  sectionOne: 'WHAT IS THE ADRESS OF THE VIOLATOR ?',
  sectionTwo: 'CONTACT INFORMATION',
  AddressAsEntered:'NEAREST ADDRESS',
  AdditionalLocationInfo:'ADDITIONAL LOCATION INFORMATION', // This Field Not in JSON, confirm with Kenyatta
  ViolatorName:'NAME OF VIOLATOR OR BUSINESS',
  IsAnonymous:'I would like to remain anonymous',
  FirstName:'FIRST NAME',
  LastName:'LAST NAME',
  Email:'EMAIL',
  ConfirmEmail:'CONFIRM EMAIL',
  Phone:'PHONE',
  RequiredFieldMessage: 'This field is required',
  formTitle:'Private Receptacle Complaint',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
}


export const formObject = {
  "ViolatorName": null,
  "IsAnonymous": false,
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": "string",
  "ServiceRequestStatusId": 0,
  "Source": null,
  "CreatedDate": null,
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "FullName": null,
  "FullNameLastFirst": null,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null
}