export const compostFormTitles = {
  sectionOne: 'SECTION 1: APPLICANT AND ORGANIZATION LOCATION',
  sectionTwo: 'SECTION 2: TERMS OF SERVICE (MUST AGREE TO ALL TERMS )',
  sectionThree: 'SECTION 3: ORGANIZATION INFORMATION',
  sectionFour: 'SECTION 4: APPLICANT CONTACT INFORMATION',
  sectionFive: 'SECTION 5: SITE INFORMATION',
  sectionSix: 'SECTION 6: DELIVERY INFORMATION',
  WillPostCompostRecipientSignage: 'Yes, I will post a DSNY compost recIpient sign near where DSNY Compost will be used.',
  WillPostSignageWithinTwoWeeks: 'Yes, the sign will be installed within two weeks of receiving the material.',
  WillSubmitThreePhotos: 'Yes, I will subming three (3) photos of the compost in use to NYCCOMPOST@DSNY.NYC.GOV.',
  ConsentToDsnyUseOfPhotos: 'Yes, photos submitted may be used for DSNY program promotion.',
  ApplyingAs: 'APPLYING AS',
  OrganizationName: 'ORGANIZATION NAME',
  OrganizationTaxIdNumber: 'ORGANIZATION TAX IDENTIFICATION NUMBER NAME',
  OrganizationWebsite: 'ORGANIZATION OR PROJECT WEBSITE (optional)',
  OrganizationFacebookPage: 'ORGANIZATION OR PROJECT FACEBOOK PAGE (optional)',
  OrganizationTwitterHandle: 'ORGANIZATION OR PROJECT TWITTER HANDLE (Optional)',
  OrganizationInstagramHandle: 'ORGANIZATION OR PROJECT instagram ID (optional)',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Title: 'YOUR TITLE OR AFFILIATION WITH ORGANIZATION (optional)',
  IsCertifiedNycMasterComposter: 'ARE YOU A CERTIFIED NYC MASTER COMPOSTER?',
  PrimaryPhone: 'PRIMARY PHONE NUMBER',
  PrimaryPhoneTypeId: 'Phone Type (optional)',
  SecondaryPhone: 'SECONDARY PHONE NUMBER (Optional)',
  SecondaryPhoneTypeId: 'Phone Type (optional)',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL',
  CompostSiteTypeId: 'WHAT TYPE OF SITE IS THIS?',
  OtherCompostSiteType: 'OTHER SITE TYPE',
  CompostSitePermittingOrganizationId: 'PERMISSION TO TEND THIS SITE WAS GRANTED BY',
  OtherCompostSitePermittingOrganization: 'OTHER PERMITTING ORGANIZATION',
  SiteSize: 'SITE SIZE (SQUARE FEET)',
  IsGreenThumbGarden: 'IS THIS A GREENTHUMB GARDEN?',
  HasReceivedDsnyCompostBefore: 'HAVE YOU RECEIVED DSNY COMPOST IN THE PAST?',
  CompostUseDescription: 'DESCRIBE HOW WILL YOU USE DSNY COMPOST? (INCLUDE SPECIFIC DATES IF KNOWN)',
  FromHourOfDayId: 'PREFERRED DELIVERY TIMES From',
  ToHourOfDayId: 'To',
  DeliveryNotes: 'DELIVERY NOTES AND INSTRUCTIONS (Optional)',
  EntranceHeightWidth: 'HEIGHT AND WIDTH OF YOUR SITE’S ENTRANCE (Optional)',
  HasAlternateSideParking: 'ALTERNATE SIDE PARKING AT SITE?',
  Pallets: 'NUMBER OF PALLETS OF COMPOST',
  DeliveryDeadline: 'WHEN IS THE LATEST DATE YOUR COMPOST IS NEEDED BY?',
  DeliveryOn: 'THE SIGN WILL BE INSTALLED WITHIN TWO WEEKS OF RECEIVING THE MATERIAL.',
  AlternateSideParking: 'ALTERNATE SIDE PARKING DAYS? (Select ALL that apply)',
  AlternateSideParkingTimes: 'PREFERRED DELIVERY TIMES From',
  RequiredFieldMessage: 'This field is required',
}

export const sharedFormTitles = {
  "FirstName": "FIRST NAME",
  "LastName": "LAST NAME",
  "Role": "ROLE/TITLE",
  "Title": "YOUR TITLE OR AFFILIATION WITH ORGANIZATION (optional)",
  "Phone": "PHONE",
  "PhoneType": "PHONE TYPE",
  "PrimaryPhone": "PRIMARY PHONE NUMBER",
  "PrimaryPhoneTypeId": "Phone Type (optional)",
  "SecondaryPhone": "SECONDARY PHONE NUMBER (Optional)",
  "SecondaryPhoneTypeId": "Phone Type (optional)",
  "Email": "E-MAIL",
  "Address": "ADDRESS",
  "AddressOpt": "ADDRESS (OPTIONAL)",
  "FLoorSuiteApt": "FLOOR/SUITE/APT (OPTIONAL)",
  "BusinessName": "NAME OF BUSINESS",
  "ResidentInfo": "Registrant Information",
  "MailingAddress": "Mailing Address (if different than business location)",
  "BusinessType": "Business Type",
  "OnsiteMethod": "ON-SITE PROCESSING METHOD",
  "EquipmentandCapacityInfo": "EQUIPMENT AND CAPACITY INFORMATION",
  "Manufacturer": "MANUFACTURER (OTPIONAL)",
  "Model": "MODEL # (OTPIONAL)",
  "DescribeSystem": "DESCRIBE YOUR SYSTEM (OTPIONAL)",
  "MinimumCapacity": "MINIMUM CAPACITY(LBS/DAY)",
  "MaximumCapacity": "MAXIMUM CAPACITY(LBS/DAY)",
  "InstallationDate": "INSTALLATION DATE (MM/DD/YYYY)",
  "GiInstall": "GREASE INTERCEPTOR INSTALLATION",
  "GiInstallOptional": "GREASE INTERCEPTOR INSTALLATION(OPTIONAL)",
  "Manufacturer": "MANUFACTURER (OPTIONAL)",
  "CapOptional": "CAPACITY (LBS)(OPTIONAL)",
  "Flow": "FLOW(UNITS PER MANUFATURER SPECS)(OPTIONAL)",
  "BusinessSelectList": "WHAT IS THE NATURE OF BUSINESS ACTIVITY AT THIS PREMISES? (SELECT ALL THAT APPLY)"
}
export const commercialOrganicsFormTitles = {
  "residentInfo": "Registrant Information",

}
  

export const eventParticipationTitle = {
  sectionOne: 'WHERE IS THE EVENT',
  Address: 'ADDRESS',
  SectionTwo:'EVENT INFORMATION',
  EventName:'EVENT NAME',
  AlternateName:'ALTERNATE NAME/SITE NAME',
  StartDate:'START DATE',
  AttendeeCountRanges:'EXPECTED # OF ATTENDEES',
  IsRecurrent:'IS THIS A RECURRING EVENT',
  PrimaryContact:'PRIMARY CONTACT INFORMATION',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Floor: 'FLOOR/SUITE/APT (OPTIONAL)',
  Title: 'TITLE',
  Organization:'ORGANIZATION',
  Phone:'PHONE',
  PhoneType:'PHONE TYPE',
  Email:'EMAIL',
  ConfirmEmail:'CONFIRM EMAIL',
  StartTime:'START TIME',
  EndTime:'END TIME',
  EndDate:'END DATE',
  ParticipatingOrganizationsDescription:'DESCRIBE PARTICIPATING ORGANIZATIONS (OPTIONAL)',
  AdditionalEventInfo:'ADDITIONAL EVENT INFO',
  ProvidedEquipmentDescription:'DECRIBE EQUIPMENT PROVIDED',
  RecyclableShippingInfo:'SHIPPING INFO FOR RECYCLING MATERIALS',
  ProvidedParkingDescription:'DESCRIBE PARKING PROVIDED',
  firstNameOptional: 'FIRST NAME (OPTIONAL)',
  lastNameOptional: 'LAST NAME (OPTIONAL)',
  SecondaryContactInfo:'SECONDARY CONTACT INFORMATION (OPTIONAL)',
  PhoneOPtional: 'PHONE (OPTIONAL)',
  PhoneTypeOptional:'PHONE TYPE (OPTIONAL)',
  EmailOptional:'EMAIL (OPTIONAL)',
  ConfirmEmailOptional:'CONFIRM EMAIL (OPTIONAL)',
  titleOptional:'TITLE (OPTIONAL',
  OrganizationOptional:'ORGANIZATION (OPTIONAL)',
  AddressOptional: 'ADDRESS (OPTIONAL)',
  FloorOptional:'FLOOR/SUITE/APT (OPTIONAL)',
  CostumeCharacterReqst: 'COSTUME CHARACTERS REQUESTED (SELECT ALL THAT APPLY)',
  ZeroWasteCan:'Zero Waste Can (garbage can)',
  BlueBin:'Blue Bin (metal,glass,plastics,cartons)',
  GreenBin:'Green bin (paper & cardboard)',
  BrownBin:'Brown  bin (organics)',
  LeafBag: 'Leaf Bag (yard waste)',

}
