export const Titles = {
  sectionOne: 'EMPLOYEE INFORMATION',
  SectionTwo:'INCIDENT DETAILS',
  SectionThree:'AGREEMENT',
  EmployeeId: 'EMPLOYEE ID',
  Title:'TITLE',
  FullNameLastFirstMi:'EMPLOYEE\'S NAME (LAST,FIRST,MI.)',
  WorkLocation:'WORK LOCATION/UNIT',
  Supervisor:'SUPERVISOR',
  Phone:'TELEPHONE',
  IncidentYear:'INCIDENT DATE',
  IncidentTime:'INCIDENT TIME',
  IncidentDescription:'THE FOLLOWING INCIDENT OCCURRED',
  ReasonForEeoInvolvement:'WHY DO YOU BELEIVE THIS INCIDENT IS AN EEO MATTER THAT SHOULD BE CONSIDERED BY THE EEO OFFICE ?',
  CheckBoxHeadingOne:'WHAT IS THE ALLEGED BASIS OF DISCRIMINATION ?',
  Race:'Race',
  Gender:'Gender',
  PartnershipStatus:'Partnership Status',
  Color:'Color',
  Disability:'Disability',
  GeneticPredisposition:'Genetic Predisposition',
  NationalOrigin:'National Origin',
  Age:'Age',
  SexualOrientation:'Sexual Orientation',
  Alienage:'Alienage',
  MilitaryStatus:'Military Status',
  DomesticViolence:'Victim of Domestic Violence',
  CitizenshipStatus:'Citizenship Status',
  PriorArrestOrConviction:'Prior Record of Arrest or Conviction',
  SexOffense:'Victim of Sex offence',
  Religion:'Religion',
  MaritalStatus:'Martial Status',
  Stalking:'Victim of Stalking',
  Creed:'Creed',
  PriorIncidents:'WAS THIS INCIDENT A FIRST OCCURENCE ? IF THERE HAVE BEEN SIMILAR OR PRIOR INCIDENTS, PLEASE DESCRIBE, GIVE THE DATE OF OCCURENCE AND PROVIDE THE WITNESS INFORMATION.',
  Witnesses:'WERE THERE ANY WITNESSES TO THIS INCIDENT (I.E., OTHERS WHO WERE NOT DIRECTLY INVOLVED, BUT WHO MAY HAVE SEEN OR HEARD WHAT TOOK PLACE) ?',
  RelatedDocumentation:'IS THERE ANY DOCUMENTATION THAT RELATES TO YOUR CLAIM ?',
  YourResponse:'WHEN THIS INCIDENT OCCURRED, HOW DID YOU RESPOND TO THE OTHER PERSON(S) DIRECTLY INVOLVED ?',
  PersonsTold:'AFTER THIS INCIDENT OCCURED, DID YOU SPEAK TO ANYONE AT WORK ABOUT WHAT HAPPENED ?',
  OtherVictims:'HAVE YOU WITNESSED ANOTHER EMPLOYEE BEING SUBJECTED TO SIMILAR BEHAVIOR/CONDUCT BY THE PERSON(S) DIRECTLY INVOLVED IN THIS INCIDENT ?',
  DesiredOutcome:'WHAT REMEDY OR ACTION WOULD YOU LIKE TAKEN TO CORRECT THIS SITUATION ?',
  Signature:'FULL NAME (LAST,FIRST,MI.)',
  SignatureDate:'DATE(MM/DD/YYYY)',
  Affirmation:'EMPLOYEE: I HAVE REVIEWED THE ENTRIES ON THIS EEO COMPLAINT FORM, AND I AFFIRM THESE STATEMENTS TO BE TRUE,TO THE BEST OF MY RECOLLECTION,I HAVE RECEIVED THE INFORMATION COVERING MY RIGHT TO FILE A COMPLAINT WITH FEDERAL,STATE, AND LOCAL CIVIL RIGHTS ENFORCEMENT AGENCIES.',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
}


export const formObject = {
  
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "ServiceRequestStatusId": 1,
  "CreatedDate": "0001-01-01T00:00:00",
  "FullNameLastFirstMi": null,
  "MiddleInitial": null,
  "EmployeeId": null,
  "Title": null,
  "WorkLocation": null,
  "Supervisor": null,
  "Phone": null,
  "IncidentMonthAndDay": null,
  "IncidentYear": 0,
  "IncidentTime": null,
  "IncidentDescription": null,
  "ReasonForEeoInvolvement": null,
  "Race": false,
  "Gender": false,
  "PartnershipStatus": false,
  "Color": false,
  "Disability": false,
  "GeneticPredisposition": false,
  "NationalOrigin": false,
  "Age": false,
  "SexualOrientation": false,
  "Alienage": false,
  "MilitaryStatus": false,
  "DomesticViolence": false,
  "CitizenshipStatus": false,
  "PriorArrestOrConviction": false,
  "SexOffense": false,
  "Religion": false,
  "MaritalStatus": false,
  "Stalking": false,
  "Creed": false,
  "PriorIncidents": null,
  "Witnesses": null,
  "RelatedDocumentation": null,
  "YourResponse": null,
  "PersonsTold": null,
  "OtherVictims": null,
  "DesiredOutcome": null,
  "Signature": null,
  "SignatureDate": null,
  "IncidentTimesArray": [
    {
      "Id":0,
      "Name":"Select One",
      "DisplayName": "Select one",
      "Selected": false
    },
    {
      "Id": 1,
      "Name": "TwelveAm",
      "DisplayName": "12:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 2,
      "Name": "OneAm",
      "DisplayName": "01:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 3,
      "Name": "TwoAm",
      "DisplayName": "02:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 4,
      "Name": "ThreeAm",
      "DisplayName": "03:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 5,
      "Name": "FourAm",
      "DisplayName": "04:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 6,
      "Name": "FiveAm",
      "DisplayName": "05:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 7,
      "Name": "SixAm",
      "DisplayName": "06:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 8,
      "Name": "SevenAm",
      "DisplayName": "07:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 9,
      "Name": "EightAm",
      "DisplayName": "08:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 10,
      "Name": "NineAm",
      "DisplayName": "09:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 11,
      "Name": "TenAm",
      "DisplayName": "10:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 12,
      "Name": "ElevenAm",
      "DisplayName": "11:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 13,
      "Name": "TwelvePm",
      "DisplayName": "12:00 PM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 14,
      "Name": "OnePm",
      "DisplayName": "01:00 PM",
      "Selected": false,
      "type":"time",
    },
    
    {
      "Id": 15,
      "Name": "TwoPm",
      "DisplayName": "02:00 PM",
      "Selected": false,
      "type":"time",
    },
 
    {
      "Id": 16,
      "Name": "ThreePm",
      "DisplayName": "03:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 17,
      "Name": "FourPm",
      "DisplayName": "04:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 18,
      "Name": "FivePm",
      "DisplayName": "05:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 19,
      "Name": "SixPm",
      "DisplayName": "06:00 PM",
      "Selected": false,
      "type":"time",
    },
    
    {
      "Id": 20,
      "Name": "SevenPm",
      "DisplayName": "07:00 PM",
      "Selected": false,
      "type":"time",
    },
 
    {
      "Id": 21,
      "Name": "EightPm",
      "DisplayName": "08:00 PM",
      "Selected": false
    },
   
    {
      "Id": 22,
      "Name": "NinePm",
      "DisplayName": "09:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 23,
      "Name": "TenPm",
      "DisplayName": "10:00 PM",
      "Selected": false,
      "type":"time",
    },
    
    {
      "Id": 24,
      "Name": "ElevenPm",
      "DisplayName": "11:00 PM",
      "Selected": false,
      "type":"time",
    },

  ],
}