export const Titles = {
  sectionOne: 'WHERE ARE THE WEEDS LOCATED',
  sectionTwo: 'CONTACT INFORMATION',
  Description: 'ADDITIONAL LOCATION INFORMATION (OPTIONAL)',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL',
  Phone: 'PHONE',
  IsAnonymous: 'I would like to remain anonymous',
  RequiredFieldMessage: 'This field is required'
}

export const formObject = { 
  "Description": null,
  "IsAnonymous": false,
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "Source": null,
  "CreatedDate": "0001-01-01T00:00:00",
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "FullName": null,
  "FullNameLastFirst": null,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null,
  "AdditionalLocationInfo": null
}