export const Titles = {
	sectionOne: 'ENTER YOUR ADDRESS',
	sectionTwo: 'SPECIFIC INFORMATION',
	sectionThree: 'CONTACT INFORMATION',
	crossStreet:'CROSS STREET',
	FirstName: 'FIRST NAME',
	LastName: 'LAST NAME',
	Phone: 'PRIMARY PHONE NUMBER',
	Email: 'E-MAIL',
	ConfirmEmail: 'CONFIRM E-MAIL',
	AppointmentDate: 'APPOINTMENT DATE',
	PickUpLocation: 'PICKUP STREET',
	overideAddressValidation:'I certify that this request is not for a commercial business or an apartment with more than 10 units.',
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
}

export const formObject = {
	"RequestId": 0,
	"buildingStatus":false,
	"commercialAddress":false,
	"overideAddressValidation":false,
	"isDistrictActive":true,
	"strRequestId": "",
	"SRNumber": "",
	"FirstName": "",
	"LastName": "",
	"Phone": "",
	"Email": "",
	"ConfirmEmail": "",
	"Borough": "",
	"BuildingNumber": "",
	"Street": "",
	"District": "",
	"DistrictName": "",
	"PickUpLocation": "",
	"BBL": "",
	"CrossStreets": "",
	"AppointmentDate": "",
	"CreatedDate": "",
	"LastUpdatedDate": "",
	"UserName": "",
	"Source": "",
	"StatusId": 0,
	"PickupRequestItems": [],
	 "categories": [
    {
      "$id": "1",
      "CategoryId": 1,
      "Category": "Televisions CRT",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": [
        {
          "$id": "1",
          "CategoryId": 1,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 1,
          "SubCategory": "Smaller than 20\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "2",
          "CategoryId": 1,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 2,
          "SubCategory": "20\" – 30\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "3",
          "CategoryId": 1,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 3,
          "SubCategory": "31\" – 40\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "4",
          "CategoryId": 1,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 4,
          "SubCategory": "41\" – 50\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "5",
          "CategoryId": 1,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 5,
          "SubCategory": "51\" – 60\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "6",
          "CategoryId": 1,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 6,
          "SubCategory": "Larger than 60\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        }
      ]
    },
    {
      "$id": "2",
      "CategoryId": 17,
      "Category": "Televisions LCD",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": [
        {
          "$id": "1",
          "CategoryId": 17,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 1,
          "SubCategory": "Smaller than 20\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "2",
          "CategoryId": 17,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 2,
          "SubCategory": "20\" – 30\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "3",
          "CategoryId": 17,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 3,
          "SubCategory": "31\" – 40\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "4",
          "CategoryId": 17,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 4,
          "SubCategory": "41\" – 50\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "5",
          "CategoryId": 17,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 5,
          "SubCategory": "51\" – 60\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        },
        {
          "$id": "6",
          "CategoryId": 17,
          "Category": null,
          "DashboardCategory": null,
          "SubCategoryId": 6,
          "SubCategory": "Larger than 60\"",
          "DashboardSubCategory": null,
          "RequestedQty": 0,
          "PickedUpQty": 0,
          "PickupRequestSubItems": null,
          "hasSubCategory": 0
        }
      ]
    },
    {
      "$id": "3",
      "CategoryId": 3,
      "Category": "Monitors, laptops",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "4",
      "CategoryId": 4,
      "Category": "Electronic keyboards",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "5",
      "CategoryId": 5,
      "Category": "Electronic mice/pointing devices",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "6",
      "CategoryId": 6,
      "Category": "Fax machines, document scanners, and printers",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "7",
      "CategoryId": 2,
      "Category": "Other computer peripherals",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "8",
      "CategoryId": 8,
      "Category": "VCRs",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "9",
      "CategoryId": 9,
      "Category": "Digital video recorders",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "10",
      "CategoryId": 10,
      "Category": "DVD players",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "11",
      "CategoryId": 11,
      "Category": "Digital converter boxes",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "12",
      "CategoryId": 12,
      "Category": "Cable/Satellite receivers",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "13",
      "CategoryId": 13,
      "Category": "Video game consoles",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "14",
      "CategoryId": 14,
      "Category": "Computer/Small scale servers",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "15",
      "CategoryId": 7,
      "Category": "Other TV peripherals",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "16",
      "CategoryId": 16,
      "Category": "Portable digital music players",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    },
    {
      "$id": "17",
      "CategoryId": 15,
      "Category": "Other portable devices",
      "DashboardCategory": null,
      "SubCategoryId": 0,
      "SubCategory": null,
      "DashboardSubCategory": null,
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": null,
      "hasSubCategory": 0
    }
  ],
}
