export const Titles = {
  sectionOne: 'ENTER YOUR ADDRESS',
  sectionTwo: 'SPECIFIC INFORMATION',
  sectionThree: 'CONTACT INFORMATION',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Phone: 'PRIMARY PHONE NUMBER',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL'
}


export const formObject = {
  "RequestId": 0,
  "strRequestId": "",
  "SRNumber": "",
  "FirstName": "",
  "LastName": "",
  "Phone": "",
  "Email": "",
  "ConfirmEmail": "",
  "Borough": "",
  "BuildingNumber": "",
  "Street": "",
  "District": "",
  "DistrictName": "",
  "PickUpLocation": "",
  "BBL": "",
  "CrossStreets": "",
  "AppointmentDate": "",
  "CreatedDate": "",
  "LastUpdatedDate": "",
  "UserName": "",
  "Source": "",
  "StatusId": 0,
  "Status": "",
  "CanCancel": 0,
  "CanReschedule": 0,
  "ReasonType": "",
  "Comments": "",
  "TruckId": 0,
  "TruckSerialNo": "",
  "MaterialTypeId": 0,
  "MaterialType": "",
  "CRTTVs": 0,
  "LCDTVs": 0,
  "TVTotal": 0,
  "OthersTotal": 0,
  "TotalRequestItems": 0,
  "RequestedCRTTVs": 0,
  "RequestedLCDTVs": 0,
  "RequestedOthersTotal": 0,
  "PickedUpCRTTVs": 0,
  "PickedUpLCDTVs": 0,
  "PickedUpOthersTotal": 0,
  "PendingRequestsTotal": 0,
  "CompletedRequestsTotal": 0,
  "NotOnLocationRequestsTotal": 0,
  "UnserviceableRequestsTotal": 0,
  "TotalPendingCRTTVs": 0,
  "TotalPendingLCDTVs": 0,
  "TotalPendingOthers": 0,
  "TotalPickedUpCRTTVs": 0,
  "TotalPickedUpLCDTVs": 0,
  "TotalPickedUpOthers": 0,
  "PendingCRTTVSmallerThan20": 0,
  "PendingCRTTV20to30": 0,
  "PendingCRTTV31to40": 0,
  "PendingCRTTV41to50": 0,
  "PendingCRTTV51to60": 0,
  "PendingCRTTVLargerThan60": 0,
  "PendingLCDTVSmallerThan20": 0,
  "PendingLCDTV20to30": 0,
  "PendingLCDTV31to40": 0,
  "PendingLCDTV41to50": 0,
  "PendingLCDTV51to60": 0,
  "PendingLCDTVLargerThan60": 0,
  "PickedUpCRTTVSmallerThan20": 0,
  "PickedUpCRTTV20to30": 0,
  "PickedUpCRTTV31to40": 0,
  "PickedUpCRTTV41to50": 0,
  "PickedUpCRTTV51to60": 0,
  "PickedUpCRTTVLargerThan60": 0,
  "PickedUpLCDTVSmallerThan20": 0,
  "PickedUpLCDTV20to30": 0,
  "PickedUpLCDTV31to40": 0,
  "PickedUpLCDTV41to50": 0,
  "PickedUpLCDTV51to60": 0,
  "PickedUpLCDTVLargerThan60": 0,
  "DistrictsList": "",
  "PickupRequestItems": [
    {
      "CategoryId": 0,
      "Category": "",
      "DashboardCategory": "",
      "SubCategoryId": 0,
      "SubCategory": "",
      "DashboardSubCategory": "",
      "RequestedQty": 0,
      "PickedUpQty": 0,
      "PickupRequestSubItems": [
        {
          "SubCategoryId": 0,
          "SubCategoryName": "",
          "CategoryId": 0,
          "CategoryName": "",
          "Quantity": 0,
          "RequestedQty": 0,
          "PickedUpQty": 0
        }
      ],
      "hasSubCategory": 0
    }
  ],
  "IsCompleteRequest": true,
  "Supervisor": "",
  "PickupRequestImages": [
    {
      "ImageID": 0,
      "ImageName": "",
      "ImageLink": "",
      "ImageLocation": "",
      "UploadedBy": "",
      "UploadedDateTime": ""
    }
  ],
  "ApplicationSource": "",
  "BulkLocation": "",
  "IsDuplicate": true
}
