export const Titles = {
  "SuccessMessage": "Success! Your response No. is: ",
  "FailureMessage":"Please make sure your message is correct.",
  "sectionOne": "BIN OWNER INFORMATION",
  "sectionTwo": "BIN INFORMATION",
  "CompanyName":"COMPANY NAME",
  "Title":"CONTACT TITLE/ROLE",
  "FirstName":"CONTACT FIRST NAME",
  "LastName":"CONTACT LAST NAME",
  "Email":"CONTACT E-MAIL",
  "Phone":"CONTACT PHONE",
  "DsnyAssignedBinId1":"DSNY ASSIGNED BIN ID 1",
  "WeightInPounds1":"WEIGHT (IN LBS)",
  "Removed1":"REMOVED",
  "RemovalDate1":"DATE REMOVED",
  "DsnyAssignedBinId2":"DSNY ASSIGNED BIN ID 2",
  "WeightInPounds2":"WEIGHT (IN LBS)",
  "Removed2":"REMOVED",
  "RemovalDate2": "DATE REMOVED",
  "DsnyAssignedBinId3":"DSNY ASSIGNED BIN ID 3",
  "WeightInPounds3":"WEIGHT (IN LBS)",
  "Removed3":"REMOVED",
  "RemovalDate3": "DATE REMOVED",
  "DsnyAssignedBinId4":"DSNY ASSIGNED BIN ID 4",
  "WeightInPounds4":"WEIGHT (IN LBS)",
  "Removed4":"REMOVED",
  "RemovalDate4": "DATE REMOVED",
  "DsnyAssignedBinId5":"DSNY ASSIGNED BIN ID 5",
  "WeightInPounds5":"WEIGHT (IN LBS)",
  "Removed5":"REMOVED",
  "RemovalDate5": "DATE REMOVED",
  "DsnyAssignedBinId6":"DSNY ASSIGNED BIN ID 6",
  "WeightInPounds6":"WEIGHT (IN LBS)",
  "Removed6":"REMOVED",
  "RemovalDate6": "DATE REMOVED",
  "DsnyAssignedBinId7":"DSNY ASSIGNED BIN ID 7",
  "WeightInPounds7":"WEIGHT (IN LBS)",
  "Removed7":"REMOVED",
  "RemovalDate7": "DATE REMOVED",
  "DsnyAssignedBinId8":"DSNY ASSIGNED BIN ID 8",
  "WeightInPounds8":"WEIGHT (IN LBS)",
  "Removed8":"REMOVED",
  "RemovalDate8": "DATE REMOVED",
  "DsnyAssignedBinId9":"DSNY ASSIGNED BIN ID 9",
  "WeightInPounds9":"WEIGHT (IN LBS)",
  "Removed9":"REMOVED",
  "RemovalDate9": "DATE REMOVED",
  "DsnyAssignedBinId10":"DSNY ASSIGNED BIN ID 10",
  "WeightInPounds10":"WEIGHT (IN LBS)",
  "Removed10":"REMOVED",
  "RemovalDate10": "DATE REMOVED",
  "DsnyAssignedBinId11":"DSNY ASSIGNED BIN ID 11",
  "WeightInPounds11":"WEIGHT (IN LBS)",
  "Removed11":"REMOVED",
  "RemovalDate11": "DATE REMOVED",
  "DsnyAssignedBinId12":"DSNY ASSIGNED BIN ID 12",
  "WeightInPounds12":"WEIGHT (IN LBS)",
  "Removed12":"REMOVED",
  "RemovalDate12": "DATE REMOVED",
  "DsnyAssignedBinId13":"DSNY ASSIGNED BIN ID 13",
  "WeightInPounds13":"WEIGHT (IN LBS)",
  "Removed13":"REMOVED",
  "RemovalDate13": "DATE REMOVED",
  "DsnyAssignedBinId14":"DSNY ASSIGNED BIN ID 14",
  "WeightInPounds14":"WEIGHT (IN LBS)",
  "Removed14":"REMOVED",
  "RemovalDate14": "DATE REMOVED",
  "DsnyAssignedBinId15":"DSNY ASSIGNED BIN ID 15",
  "WeightInPounds15":"WEIGHT (IN LBS)",
  "Removed15":"REMOVED",
  "RemovalDate15": "DATE REMOVED",
  "DsnyAssignedBinId16":"DSNY ASSIGNED BIN ID 16",
  "WeightInPounds16":"WEIGHT (IN LBS)",
  "Removed16":"REMOVED",
  "RemovalDate16": "DATE REMOVED",
  "DsnyAssignedBinId17":"DSNY ASSIGNED BIN ID 17",
  "WeightInPounds17":"WEIGHT (IN LBS)",
  "Removed17":"REMOVED",
  "RemovalDate17": "DATE REMOVED",
  "DsnyAssignedBinId18":"DSNY ASSIGNED BIN ID 18",
  "WeightInPounds18":"WEIGHT (IN LBS)",
  "Removed18":"REMOVED",
  "RemovalDate18": "DATE REMOVED",
  "DsnyAssignedBinId19":"DSNY ASSIGNED BIN ID 19",
  "WeightInPounds19":"WEIGHT (IN LBS)",
  "Removed19":"REMOVED",
  "RemovalDate19": "DATE REMOVED",
  "DsnyAssignedBinId20":"DSNY ASSIGNED BIN ID 20",
  "WeightInPounds20":"WEIGHT (IN LBS)",
  "Removed20":"REMOVED",
  "RemovalDate20": "DATE REMOVED",
  "DsnyAssignedBinId21":"DSNY ASSIGNED BIN ID 21",
  "WeightInPounds21":"WEIGHT (IN LBS)",
  "Removed21":"REMOVED",
  "RemovalDate21": "DATE REMOVED",
  "DsnyAssignedBinId22":"DSNY ASSIGNED BIN ID 22",
  "WeightInPounds22":"WEIGHT (IN LBS)",
  "Removed22":"REMOVED",
  "RemovalDate22": "DATE REMOVED",
  "DsnyAssignedBinId23":"DSNY ASSIGNED BIN ID 23",
  "WeightInPounds23":"WEIGHT (IN LBS)",
  "Removed23":"REMOVED",
  "RemovalDate23": "DATE REMOVED",
  "DsnyAssignedBinId24":"DSNY ASSIGNED BIN ID 24",
  "WeightInPounds24":"WEIGHT (IN LBS)",
  "Removed24":"REMOVED",
  "RemovalDate24": "DATE REMOVED",
  "DsnyAssignedBinId25":"DSNY ASSIGNED BIN ID 25",
  "WeightInPounds25":"WEIGHT (IN LBS)",
  "Removed25":"REMOVED",
  "RemovalDate25": "DATE REMOVED",
}

export const formObject = {
    "Id": 0,
    "SRNumberId": 0,
    "SRNo": "",
    "ServiceRequestStatusId": 0,
    "CreatedDate": "2017-11-21T20:15:10.688Z",
    "FirstName": "",
    "LastName": "",
    "Phone": "",
    "Email": "",
    "FullName": "",
    "FullNameLastFirst": "",
    "CompanyName": "",
    "Title": "",
    "BinCount": 1,
    "CollectionBins": [
      {
        "DsnyAssignedBinId": "",
        "WeightInPounds": 0,
        "Removed": true,
        "RemovalDate": ""
      },
      {
        "DsnyAssignedBinId": "",
        "WeightInPounds": 0,
        "Removed": true,
        "RemovalDate": ""
      },
      {
        "DsnyAssignedBinId": "",
        "WeightInPounds": 0,
        "Removed": true,
        "RemovalDate": ""
      },
      {
        "DsnyAssignedBinId": "",
        "WeightInPounds": 0,
        "Removed": true,
        "RemovalDate": ""
      }
    ],

    "DsnyAssignedBinId1": 0,
    "WeightInPounds1": 0,
    "Removed1": null,
    "RemovalDate1": "",
    "DsnyAssignedBinId2": 0,
    "WeightInPounds2": 0,
    "Removed2": null,
    "RemovalDate2": "",
    "DsnyAssignedBinId3": 0,
    "WeightInPounds3": 0,
    "Removed3": null,
    "RemovalDate3": "",
    "DsnyAssignedBinId4": 0,
    "WeightInPounds4": 0,
    "Removed4": null,
    "RemovalDate4": "",
    "DsnyAssignedBinId5": 0,
    "WeightInPounds5": 0,
    "Removed5": null,
    "RemovalDate5": "",
    "DsnyAssignedBinId6": 0,
    "WeightInPounds6": 0,
    "Removed6": null,
    "RemovalDate6": "",
    "DsnyAssignedBinId7": 0,
    "WeightInPounds7": 0,
    "Removed7": null,
    "RemovalDate7": "",
    "DsnyAssignedBinId8": 0,
    "WeightInPounds8": 0,
    "Removed8": null,
    "RemovalDate8": "",
    "DsnyAssignedBinId9": 0,
    "WeightInPounds9": 0,
    "Removed9": null,
    "RemovalDate9": "",
    "DsnyAssignedBinId10": 0,
    "WeightInPounds10": 0,
    "Removed10": null,
    "RemovalDate10": "",
    "DsnyAssignedBinId11": 0,
    "WeightInPounds11": 0,
    "Removed11": null,
    "RemovalDate11": "",
    "DsnyAssignedBinId12": 0,
    "WeightInPounds12": 0,
    "Removed12": null,
    "RemovalDate12": "",
    "DsnyAssignedBinId13": 0,
    "WeightInPounds13": 0,
    "Removed13": null,
    "RemovalDate13": "",
    "DsnyAssignedBinId14": 0,
    "WeightInPounds14": 0,
    "Removed14": null,
    "RemovalDate14": "",
    "DsnyAssignedBinId15": 0,
    "WeightInPounds15": 0,
    "Removed15": null,
    "RemovalDate15": "",
    "DsnyAssignedBinId16": 0,
    "WeightInPounds16": 0,
    "Removed16": null,
    "RemovalDate16": "",
    "DsnyAssignedBinId17": 0,
    "WeightInPounds17": 0,
    "Removed17": null,
    "RemovalDate17": "",
    "DsnyAssignedBinId18": 0,
    "WeightInPounds18": 0,
    "Removed18": null,
    "RemovalDate18": "",
    "DsnyAssignedBinId19": 0,
    "WeightInPounds19": 0,
    "Removed19": null,
    "RemovalDate19": "",
    "DsnyAssignedBinId20": 0,
    "WeightInPounds20": 0,
    "Removed20": null,
    "RemovalDate20": "",
    "DsnyAssignedBinId21": 0,
    "WeightInPounds21": 0,
    "Removed21": null,
    "RemovalDate21": "",
    "DsnyAssignedBinId22": 0,
    "WeightInPounds22": 0,
    "Removed22": null,
    "RemovalDate22": "",
    "DsnyAssignedBinId23": 0,
    "WeightInPounds23": 0,
    "Removed23": null,
    "RemovalDate23": "",
    "DsnyAssignedBinId24": 0,
    "WeightInPounds24": 0,
    "Removed24": null,
    "RemovalDate24": "",
    "DsnyAssignedBinId25": 0,
    "WeightInPounds25": 0,
    "Removed25": null,
    "RemovalDate25": "",
}

// "Id": 0,
// "DsnyAssignedBinId": 0,



// "DsnyAssignedBinId": 0,
// "WeightInPounds": 0,
// "Removed": false,
// "DsnyAssignedBinId2": 0,
// "WeightInPounds2": 0,
// "Removed2": false,
