export const Titles = {
  "sectionOne": "BIN OWNER INFORMATION",
  "sectionTwo": "BIN INFORMATION",
  "CompanyName":"COMPANY NAME",
  "Title":"CONTACT TITLE/ROLE",
  "FirstName":"CONTACT FIRST NAME",
  "LastName":"CONTACT LAST NAME",
  "Email":"CONTACT E-MAIL",
  "Phone":"CONTACT PHONE",
  "CollectionBinAnnualReportId":"DSNY ASSIGNED BIN ID 1",
  "WeightInPounds":"WEIGHT (IN LBS)",
  "Removed":"REMOVED",
  "CollectionBinAnnualReportId2":"DSNY ASSIGNED BIN ID 2",
  "WeightInPounds2":"WEIGHT (IN LBS)",
  "Removed2":"REMOVED",
  "CollectionBinAnnualReportId3":"DSNY ASSIGNED BIN ID 3",
  "WeightInPounds3":"WEIGHT (IN LBS)",
  "Removed3":"REMOVED",
  "CollectionBinAnnualReportId4":"DSNY ASSIGNED BIN ID 4",
  "WeightInPounds4":"WEIGHT (IN LBS)",
  "Removed4":"REMOVED",
  "CollectionBinAnnualReportId5":"DSNY ASSIGNED BIN ID 5",
  "WeightInPounds5":"WEIGHT (IN LBS)",
  "Removed5":"REMOVED",
  "CollectionBinAnnualReportId6":"DSNY ASSIGNED BIN ID 6",
  "WeightInPounds6":"WEIGHT (IN LBS)",
  "Removed6":"REMOVED",
  "CollectionBinAnnualReportId7":"DSNY ASSIGNED BIN ID 7",
  "WeightInPounds7":"WEIGHT (IN LBS)",
  "Removed7":"REMOVED",
  "CollectionBinAnnualReportId8":"DSNY ASSIGNED BIN ID 8",
  "WeightInPounds8":"WEIGHT (IN LBS)",
  "Removed8":"REMOVED",
  "CollectionBinAnnualReportId9":"DSNY ASSIGNED BIN ID 9",
  "WeightInPounds9":"WEIGHT (IN LBS)",
  "Removed9":"REMOVED",
  "CollectionBinAnnualReportId10":"DSNY ASSIGNED BIN ID 10",
  "WeightInPounds10":"WEIGHT (IN LBS)",
  "Removed10":"REMOVED",
  "CollectionBinAnnualReportId11":"DSNY ASSIGNED BIN ID 11",
  "WeightInPounds11":"WEIGHT (IN LBS)",
  "Removed11":"REMOVED",
  "CollectionBinAnnualReportId12":"DSNY ASSIGNED BIN ID 12",
  "WeightInPounds12":"WEIGHT (IN LBS)",
  "Removed12":"REMOVED",
  "CollectionBinAnnualReportId13":"DSNY ASSIGNED BIN ID 13",
  "WeightInPounds13":"WEIGHT (IN LBS)",
  "Removed13":"REMOVED",
  "CollectionBinAnnualReportId14":"DSNY ASSIGNED BIN ID 14",
  "WeightInPounds14":"WEIGHT (IN LBS)",
  "Removed14":"REMOVED",
  "CollectionBinAnnualReportId15":"DSNY ASSIGNED BIN ID 15",
  "WeightInPounds15":"WEIGHT (IN LBS)",
  "Removed15":"REMOVED",
  "CollectionBinAnnualReportId16":"DSNY ASSIGNED BIN ID 16",
  "WeightInPounds16":"WEIGHT (IN LBS)",
  "Removed16":"REMOVED",
  "CollectionBinAnnualReportId17":"DSNY ASSIGNED BIN ID 17",
  "WeightInPounds17":"WEIGHT (IN LBS)",
  "Removed17":"REMOVED",
  "CollectionBinAnnualReportId18":"DSNY ASSIGNED BIN ID 18",
  "WeightInPounds18":"WEIGHT (IN LBS)",
  "Removed18":"REMOVED",
  "CollectionBinAnnualReportId19":"DSNY ASSIGNED BIN ID 19",
  "WeightInPounds19":"WEIGHT (IN LBS)",
  "Removed19":"REMOVED",
  "CollectionBinAnnualReportId20":"DSNY ASSIGNED BIN ID 20",
  "WeightInPounds20":"WEIGHT (IN LBS)",
  "Removed20":"REMOVED",
  "CollectionBinAnnualReportId21":"DSNY ASSIGNED BIN ID 21",
  "WeightInPounds21":"WEIGHT (IN LBS)",
  "Removed21":"REMOVED",
  "CollectionBinAnnualReportId22":"DSNY ASSIGNED BIN ID 22",
  "WeightInPounds22":"WEIGHT (IN LBS)",
  "Removed22":"REMOVED",
  "CollectionBinAnnualReportId23":"DSNY ASSIGNED BIN ID 23",
  "WeightInPounds23":"WEIGHT (IN LBS)",
  "Removed23":"REMOVED",
  "CollectionBinAnnualReportId24":"DSNY ASSIGNED BIN ID 24",
  "WeightInPounds24":"WEIGHT (IN LBS)",
  "Removed24":"REMOVED",
  "CollectionBinAnnualReportId25":"DSNY ASSIGNED BIN ID 25",
  "WeightInPounds25":"WEIGHT (IN LBS)",
  "Removed25":"REMOVED",
}

export const formObject = {
    "Id": 0,
    "SRNumberId": 0,
    "SRNo": null,
    "ServiceRequestStatusId": 0,
    "CreatedDate": "0001-01-01T00:00:00",
    "FirstName": null,
    "LastName": null,
    "Phone": null,
    "Email": null,
    "FullName": null,
    "FullNameLastFirst": null,
    "CompanyName": null,
    "Title": null,
    "CollectionBins": []
}
