export const Titles = {
"sectionOne": "BUSINESS LOCATION ADDRESS",
"sectionTwo": "REGISTRANT INFORMATION",
"sectionThree": "MAILING ADDRESS(IF DIFFERENT THAN BUSINESS LOCATION)",
"sectionFour": "BUSINESS TYPE",
"sectionFive": "ON-SITE PROCESSING METHOD",
"sectionSix": "EQUIPMENT AND CAPACITY INFORMATION",
"sectionSeven": "GREASE INTERCEPTOR INSTALLATION",
"RegistrantFirstName": "FIRST NAME",
"RegistrantLastName": "LAST NAME",
"RegistrantTitle": "ROLE/TITLE",
"Title": "YOUR TITLE OR AFFILIATION WITH ORGANIZATION (optional)",
"RegistrantPhone": "PHONE",
"RegistrantPhoneTypeId": "PHONE TYPE",
"PrimaryPhone": "PRIMARY PHONE NUMBER",
"PrimaryPhoneTypeId": "Phone Type (optional)",
"SecondaryPhone": "SECONDARY PHONE NUMBER (Optional)",
"SecondaryPhoneTypeId": "Phone Type (optional)",
"RegistrantEmail": "E-MAIL",
"Address": "ADDRESS",
"AddressAsEntered": "ADDRESS (OPTIONAL)",
"Apartment": "FLOOR/SUITE/APT (OPTIONAL)",
"MailingApartment": "FLOOR/SUITE/APT (OPTIONAL)",
"RegistrantBusinessName": "NAME OF BUSINESS",
"ResidentInfo": "Registrant Information",
"MailingAddress": "Mailing Address (if different than business location)",
"BusinessType": "Business Type",
"OnsiteMethod": "ON-SITE PROCESSING METHOD",
"EquipmentandCapacityInfo": "EQUIPMENT AND CAPACITY INFORMATION",
"EquipmentManufacturer": "MANUFACTURER (OTPIONAL)",
"EquipmentModelNo": "MODEL # (OTPIONAL)",
"EquipmentDescribeSystem": "DESCRIBE YOUR SYSTEM (OTPIONAL)",
"EquipmentMinimumCapacity": "MINIMUM CAPACITY(LBS/DAY)",
"EquipmentMaximumCapacity": "MAXIMUM CAPACITY(LBS/DAY)",
"InstallationDate": "INSTALLATION DATE (MM/DD/YYYY)",
"GreaseInterceptorTypeId": "GREASE INTERCEPTOR INSTALLATION (OPTIONAL)",
"GreaseInterceptorManufacturer": "MANUFACTURER (OPTIONAL)",
"GreaseInterceptorModelNo": "MODEL # (OPTIONAL)",
"GreaseInterceptorCapacity": "CAPACITY (LBS)(OPTIONAL)",
"GreaseInterceptorFlow": "FLOW(UNITS PER MANUFATURER SPECS)(OPTIONAL)",
"BusinessActivityTypes": "WHAT IS THE NATURE OF BUSINESS ACTIVITY AT THIS PREMISES? (SELECT ALL THAT APPLY)",
"OnsitePMOptions": "ON-SITE PROCESSING METHOD (SELECT ALL THAT APPLY)",
"OtherDescribe": "PLEASE DESCRIBE"
}

export const formObject = {
    "Id": 0,
    "SRNumberId": 0,
    "SRNo": null,
    "ServiceRequestStatusId": 0,
    "CreatedDate": "0001-01-01T00:00:00",
    "FirstName": null,
    "LastName": null,
    "Phone": null,
    "Email": null,
    "FullName": null,
    "FullNameLastFirst": null,
    "CompanyName": null,
    "Title": null,
    "CollectionBins": []
}
