export const Titles = {
  sectionOne: 'DESCRIBE SETOUT LOCATION OF RECYCLABLE MATERIAL',
  sectionTwo: 'SPECIFIC INFORMATION',
  sectionThree:'CONTACT INFORMATION',
  AddressAsEntered:'NEAREST ADDRESS',
  AdditionalLocationInfo:'ADDITIONAL LOCATION INFORMATION (OPTIONAL)',
  Description:'DESCRIBE WHAT HAPPENED',
  IncidentDate:'INCIDENT DATE',
  IncidentTime:'INCIDENT TIME',
  LicensePlateNumber:'DSNY TRUCK LICENSE PLATE NUMBER (OPTIONAL)',
  TruckNumber:'DSNY TRUCK NUMBER (OPTIONAL)',
  FirstName:'FIRST NAME',
  LastName:'LAST NAME',
  Email:'EMAIL',
  ConfirmEmail:'CONFIRM EMAIL',
  Phone:'PHONE',
  RequiredFieldMessage: 'This field is required',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
}


export const formObject = {
  
  "AdditionalLocationInfo": null,
  "Description": null,
  "IncidentDate": null,
  "IncidentTime": null,
  "LicensePlateNumber": null,
  "TruckNumber": null,
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "ServiceRequestStatusId": 0,
  "Source": null,
  "CreatedDate": null,
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "FullName": null,
  "FullNameLastFirst": null,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null,
  "IncidentTimes": [
   {
      "Id":0,
      "Name":"Select One",
      "DisplayName": "Select one",
      "Selected": false
    },
    {
      "Id": 1,
      "Name": "TwelveAm",
      "DisplayName": "12:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 2,
      "Name": "OneAm",
      "DisplayName": "01:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 3,
      "Name": "TwoAm",
      "DisplayName": "02:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 4,
      "Name": "ThreeAm",
      "DisplayName": "03:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 5,
      "Name": "FourAm",
      "DisplayName": "04:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 6,
      "Name": "FiveAm",
      "DisplayName": "05:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 7,
      "Name": "SixAm",
      "DisplayName": "06:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 8,
      "Name": "SevenAm",
      "DisplayName": "07:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 9,
      "Name": "EightAm",
      "DisplayName": "08:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 10,
      "Name": "NineAm",
      "DisplayName": "09:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 11,
      "Name": "TenAm",
      "DisplayName": "10:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 12,
      "Name": "ElevenAm",
      "DisplayName": "11:00 AM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 13,
      "Name": "TwelvePm",
      "DisplayName": "12:00 PM",
      "Selected": false,
      "type":"time",
    },
    {
      "Id": 14,
      "Name": "OnePm",
      "DisplayName": "01:00 PM",
      "Selected": false,
      "type":"time",
    },
    
    {
      "Id": 15,
      "Name": "TwoPm",
      "DisplayName": "02:00 PM",
      "Selected": false,
      "type":"time",
    },
 
    {
      "Id": 16,
      "Name": "ThreePm",
      "DisplayName": "03:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 17,
      "Name": "FourPm",
      "DisplayName": "04:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 18,
      "Name": "FivePm",
      "DisplayName": "05:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 19,
      "Name": "SixPm",
      "DisplayName": "06:00 PM",
      "Selected": false,
      "type":"time",
    },
    
    {
      "Id": 20,
      "Name": "SevenPm",
      "DisplayName": "07:00 PM",
      "Selected": false,
      "type":"time",
    },
 
    {
      "Id": 21,
      "Name": "EightPm",
      "DisplayName": "08:00 PM",
      "Selected": false
    },
   
    {
      "Id": 22,
      "Name": "NinePm",
      "DisplayName": "09:00 PM",
      "Selected": false,
      "type":"time",
    },
  
    {
      "Id": 23,
      "Name": "TenPm",
      "DisplayName": "10:00 PM",
      "Selected": false,
      "type":"time",
    },
    
    {
      "Id": 24,
      "Name": "ElevenPm",
      "DisplayName": "11:00 PM",
      "Selected": false,
      "type":"time",
    },
 
  ],
}