export const Titles = {
  sectionOne: 'WHERE IS LITTER BASKET LOCATED',
  sectionTwo: 'CONTACT INFORMATION',
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  Email: 'E-MAIL',
  ConfirmEmail: 'CONFIRM E-MAIL',
  Phone: 'PHONE',
  IsAnonymous: 'I would like to remain anonymous',
  AdditionalLocationInfo: 'ADDITIONAL LOCATION INFORMATION (OPTIONAL)',
  Message: "MESSAGE",
  SuccessMessage: "Success! Your response No. is: ",
  FailureMessage:"Please make sure your message is correct.",
  RequiredFieldMessage: 'This field is required',
}

export const formObject = {

  "AdditionalLocationInfo": null,
  "IsAnonymous": false,
  "Id": 0,
  "SRNumberId": 0,
  "SRNo": null,
  "ServiceRequestStatusId": 0,
  "Source": null,
  "CreatedDate": "0001-01-01T00:00:00",
  "FirstName": null,
  "LastName": null,
  "Phone": null,
  "Email": null,
  "FullName": null,
  "FullNameLastFirst": null,
  "AddressAsEntered": null,
  "HouseNumber": null,
  "Street": null,
  "Apartment": null,
  "Borough": null,
  "City": null,
  "State": null,
  "Zip": null,
  "District": null,
  "Section": null,
  "BBL": null,
  "Latitude": 0,
  "Longitude": 0,
  "AddressText": null,
  "AddressTextOneLine": null
  
}