  export const Titles = {
  "sectionOne": "WHERE IS THE VIOLATION OCCURRING",
  "sectionTwo": "VIOLATOR NAME AND ADDRESS",
  "sectionThree": "CONTACT INFORMATION",
  "Apartment": "ADDTIONAL LOCATION INFORMATION (OPTIONAL)",
  "ViolatorName": "NANE OF VIOLATOR OR BUSINESS",
  "ViolatorAddressAsEntered": "ADDRESS",
  "ViolatorApartment": "FLOOR/SUITE/APT (OPTIONAL)",
  "TimeOfOccurrence": "TIME OF OCCURRENCE",
  "": "WHEN ARE THE RECEPTACLES BEING PLACED OUT?",
  "FirstName": "FIRST NAME",
  "LastName": "LAST NAME",
  "Email": "E-MAIL",
  "ConfirmEmail": "CONFIRM E-MAIL",
  "Phone": "PHONE",
  "IsAnonymous": "I would like to remain anonymous",






  // "RemovedMaterialsDescription": "DESCRIBE MATERIALS REMOVED (OPTIONAL)",
  // "IncidentDate": "INCIDENT DATE (OPTIONAL)",
  // "IncidentTime": "INCIDENT TIME (OPTIONAL)",
  // "VehicleLicensePlateNumber": "VEHICLE LICENSE PLATE# (OPTIONAL)",
  // "VehicleState": "LICENSED STATE (OPTIONAL)",
  // "VehicleMake": "VEHICLE MAKE (OPTIONAL)",
  // "VehicleModel": "VEHICLE MODEL (OPTIONAL)",
  // "VehicleColor": "VEHICLE COLOR (OPTIONAL)",
  // "VehicleType": "VEHICLE TYPE (OPTIONAL)",
  // "AdditionalVehicleInfo": "ADDTIONAL VEHICLE DESCRIPTION (DENTS, COMPANY NAME, ETC.) (OPTIONAL)",
  // "FirstName": "FIRST NAME",
  // "LastName": "LAST NAME",
  // "Email": "E-MAIL",
  // "ConfirmEmail": "CONFIRM E-MAIL",
  // "Phone": "PHONE",
  // "IsAnonymous": "I would like to remain anonymous",
  // "IsVehicleCommercial": "Commercial License"
}

export const formObject = {
    "ViolatorName": null,
    "ViolatorAddressAsEntered": null,
    "ViolatorHouseNumber": null,
    "ViolatorStreet": null,
    "ViolatorApartment": null,
    "ViolatorBorough": null,
    "ViolatorCity": null,
    "ViolatorState": null,
    "ViolatorZip": null,
    "TimeOfOccurrence": null,
    "PreCollection": false,
    "PostCollection": false,
    "IsAnonymous": false,
    "Id": 0,
    "SRNumberId": 0,
    "SRNo": null,
    "ServiceRequestStatusId": 1,
    "Source": null,
    "CreatedDate": "0001-01-01T00:00:00",
    "FirstName": null,
    "LastName": null,
    "Phone": null,
    "Email": null,
    "FullName": null,
    "FullNameLastFirst": null,
    "AddressAsEntered": null,
    "HouseNumber": null,
    "Street": null,
    "Apartment": null,
    "Borough": null,
    "City": null,
    "State": "NY",
    "Zip": null,
    "District": null,
    "Section": null,
    "BBL": null,
    "Latitude": 0,
    "Longitude": 0,
    "AddressText": ", NY",
    "AddressTextOneLine": ", NY"
}
